/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as helpers_corsHelper from "../helpers/corsHelper.js";
import type * as helpers_corsHttpRouter from "../helpers/corsHttpRouter.js";
import type * as http from "../http.js";
import type * as myFunctions from "../myFunctions.js";
import type * as myHttpApi from "../myHttpApi.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "helpers/corsHelper": typeof helpers_corsHelper;
  "helpers/corsHttpRouter": typeof helpers_corsHttpRouter;
  http: typeof http;
  myFunctions: typeof myFunctions;
  myHttpApi: typeof myHttpApi;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
